"""empty message

Revision ID: 1c6c1eb27c4f
Revises: 9ba398aa37e8
Create Date: 2025-05-20 12:54:43.669396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6c1eb27c4f'
down_revision = '9ba398aa37e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('capacidad_max', sa.Integer(), nullable=True),
    sa.Column('reservas_actuales', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_matricula'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_bloque', sa.Integer(), nullable=True),
    sa.Column('id_matricula', sa.Integer(), nullable=True),
    sa.Column('fecha_reserva', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duracion_horas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_bloque'], ['bloques.id'], ),
    sa.ForeignKeyConstraint(['id_matricula'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=True),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.Column('fecha_asistencia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_reserva')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_asistencia', sa.Integer(), nullable=True),
    sa.Column('numero_clase_dia', sa.Integer(), nullable=False),
    sa.Column('id_instructor', sa.Integer(), nullable=True),
    sa.Column('id_auto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_asistencia'], ['asistencias.id'], ),
    sa.ForeignKeyConstraint(['id_auto'], ['autos.id'], ),
    sa.ForeignKeyConstraint(['id_instructor'], ['instructores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_asistencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('asistencias')
    op.drop_table('reservas')
    op.drop_table('pagos')
    op.drop_table('bloques')
    # ### end Alembic commands ###
