"""empty message

Revision ID: 235b8fd3e4ec
Revises: 5eb6c74331f9
Create Date: 2025-05-25 18:17:24.482703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235b8fd3e4ec'
down_revision = '5eb6c74331f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_contratacion', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('horas_contratadas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tarifa_por_hora', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('costo_total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_column('costo_total')
        batch_op.drop_column('tarifa_por_hora')
        batch_op.drop_column('horas_contratadas')
        batch_op.drop_column('tipo_contratacion')

    # ### end Alembic commands ###
