"""empty message

Revision ID: 28f6b2548efd
Revises: 5a4988d39b92
Create Date: 2025-06-09 19:05:45.126707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f6b2548efd'
down_revision = '5a4988d39b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    with op.batch_alter_table('instructores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructores', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
