"""empty message

Revision ID: 5a4988d39b92
Revises: 235b8fd3e4ec
Create Date: 2025-05-27 15:34:29.798426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a4988d39b92'
down_revision = '235b8fd3e4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', mysql.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
