"""empty message

Revision ID: 5eb6c74331f9
Revises: eaaacfbb8efb
Create Date: 2025-05-25 12:58:34.931249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eb6c74331f9'
down_revision = 'eaaacfbb8efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquetes', schema=None) as batch_op:
        batch_op.alter_column('horas_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('costo_total',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquetes', schema=None) as batch_op:
        batch_op.alter_column('costo_total',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('horas_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
