"""empty message

Revision ID: 9ba398aa37e8
Revises: 9a2c7df4173b
Create Date: 2025-05-20 11:11:18.381507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba398aa37e8'
down_revision = '9a2c7df4173b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paquetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('id_tipo_auto', sa.Integer(), nullable=True),
    sa.Column('horas_total', sa.Integer(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_auto'], ['tipos_auto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=True),
    sa.Column('id_paquete', sa.Integer(), nullable=True),
    sa.Column('fecha_matricula', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('ultima_modificacion_reserva', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['id_paquete'], ['paquetes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matriculas')
    op.drop_table('paquetes')
    # ### end Alembic commands ###
