"""Inicial

Revision ID: a89901aa7e1b
Revises: 
Create Date: 2025-05-20 01:46:36.935475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89901aa7e1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contraseña_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
