"""empty message

Revision ID: a9efc0ac07b4
Revises: 28f6b2548efd
Create Date: 2025-06-14 11:10:26.806246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9efc0ac07b4'
down_revision = '28f6b2548efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_completadas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_column('horas_completadas')

    # ### end Alembic commands ###
