"""empty message

Revision ID: d674ef08addf
Revises: 1c6c1eb27c4f
Create Date: 2025-05-20 17:01:58.644069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd674ef08addf'
down_revision = '1c6c1eb27c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('instructores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('fecha_actualizado')
        batch_op.drop_column('fecha_creado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creado', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizado', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('instructores', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('fecha_actualizado')
        batch_op.drop_column('fecha_creado')

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('fecha_actualizado')
        batch_op.drop_column('fecha_creado')

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('fecha_actualizado')
        batch_op.drop_column('fecha_creado')

    # ### end Alembic commands ###
