"""empty message

Revision ID: e4627196eaf8
Revises: b47a18a5f525
Create Date: 2025-05-24 19:54:25.102920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4627196eaf8'
down_revision = 'b47a18a5f525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_pago', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado_clases', sa.String(length=20), nullable=True))
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('estado_clases')
        batch_op.drop_column('estado_pago')

    # ### end Alembic commands ###
