"""empty message

Revision ID: eaaacfbb8efb
Revises: e4627196eaf8
Create Date: 2025-05-25 02:30:46.264387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaaacfbb8efb'
down_revision = 'e4627196eaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_clase_alumno', sa.Integer(), nullable=False))
        batch_op.drop_column('numero_clase_dia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_clase_dia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('numero_clase_alumno')

    # ### end Alembic commands ###
