name: Tareas Programadas

on:
  schedule:
    - cron: '0 7 * * 0'   # Cada domingo 2AM
    - cron: '0 11 * * *'  # Cada dia 6AM
  workflow_dispatch:

jobs:
  mantenimiento:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 7 * * 0' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Despertar Servidor
      run: |
        echo "Despertando servidor..."
        curl --max-time 60 --connect-timeout 30 -f "${{ secrets.API_URL }}/api" || echo "Servidor despertando..."
        sleep 5
        echo "✅ Servidor listo"

    - name: Despertar Base de Datos
      run: |
        echo "Despertando Base de datos..."
        curl --max-time 60 --connect-timeout 15 -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          "${{ secrets.API_URL }}/api/admin-tareas/despertar-bd"
        sleep 5
        echo "✅ Base de datos listo"
    
    - name: Generar Bloques
      run: |
        echo "Generando bloques..."
        curl --max-time 60 --connect-timeout 15 -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"semanas": 2}' \
          "${{ secrets.API_URL }}/api/admin-tareas/generar-bloques"
        echo "Bloques generados ✅"
    
    - name: Limpiar Bloques
      run: |
        echo "Limpiando bloques..."
        curl --max-time 60 --connect-timeout 15 -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          "${{ secrets.API_URL }}/api/admin-tareas/limpiar-bloques"
        echo "Bloques limpiados ✅"

  recordatorios-diarios:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 11 * * *' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Despertar Servidor
      run: |
        echo "Despertando servidor..."
        curl --max-time 60 --connect-timeout 30 -f "${{ secrets.API_URL }}/api" || echo "Servidor despertando..."
        sleep 5
        echo "✅ Servidor listo"

    - name: Despertar Base de Datos
      run: |
        echo "Despertando Base de datos..."
        curl --max-time 60 --connect-timeout 15 -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          "${{ secrets.API_URL }}/api/admin-tareas/despertar-bd"
        sleep 5
        echo "✅ Base de datos listo"

    - name: Enviar Recordatorios de Reservas
      run: |
        echo "Enviando recordatorios de reservas..."
        curl --max-time 60 --connect-timeout 15 -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          "${{ secrets.API_URL }}/api/admin-tareas/enviar-recordatorio-reserva"
        echo "Recordatorios enviados ✅"
        
    - name: Enviar Recordatorios de Pagos Pendientes
      run: |
        echo "Enviando recordatorios de pagos..."
        curl --max-time 60 --connect-timeout 15 -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          "${{ secrets.API_URL }}/api/admin-tareas/enviar-pagos-pendientes"
        echo "Pagos recordados ✅"   